#!/usr/bin/env zsh

if [[ ".emacs.d" != "${PWD##*/}" ]]; then echo "Execute this command from the .emacs.d directory."; return 1; fi

echo "Is your distro considered \"stable\"? (Y/n)"
read proceed
if [[ "$proceed" == "y" || "$proceed" == "Y" || "$proceed" == "" ]]; then
	sed -i -e 's@(electric-pair-mode 1)@;(electric-pair-mode 1)@' init.el
	sed -i -e 's@(global-prettify-symbols-mode 1)@;(global-prettify-symbols-mode 1)@' init.el
fi
unset proceed

wget http://www.emacswiki.org/emacs/download/iy-go-to-char.el
mkdir packages/iy-go-to-char.el
mv iy-go-to-char.el packages/iy-go-to-char.el