#!/usr/bin/env zsh

echo "Is your distro considered \"stable\"? (Y/n)"
read proceed
if [[ "$proceed" == "y" || "$proceed" == "Y" || "$proceed" == "" ]]; then
	sed -i -e 's@(electric-pair-mode 1)@;(electric-pair-mode 1)@' init.el
	sed -i -e 's@(global-prettify-symbols-mode 1)@;(global-prettify-symbols-mode 1)@' init.el
fi
unset proceed

wget http://www.emacswiki.org/emacs/download/iy-go-to-char.el
mkdir individual-packages/iy-go-to-char.el
mv iy-go-to-char.el individual-packages/iy-go-to-char.el